version: '2'
services:
  puppet:
    image: webcenter/rancher-optimize-database:${IMAGE_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}